export const SET_GENRE_LIST = "SET_GENRE_LIST"
export const SET_SELECTED_MOVIE = "SET_SELECTED_MOVIE"
export const SET_IS_LOADING_TRUE = "SET_IS_LOADING_TRUE"
export const SET_IS_LOADING_FALSE = "SET_IS_LOADING_FALSE"
